name: Mock Github actions workflow
run-name: Mock Github actions for ${{ github.actor }}
on: [push]
jobs:
  Pretend-to-do-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker
        working-directory: .
        run: docker build . -t mock_proj --file Dockerfile.final
      - name: Push Docker
        working-directory: .
        run: docker push mock_proj
